### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by michiwieland** [michiwieland/openairmalans-theme#3]
## Navigation
- [ ] CSS Class "move-to-trigger" für die Menü einträge setzen
- [ ] Social Media Komponente für das Menü anzeigen (only Font Awesome Icon)

## News
- [ ] Maximal 4 News beiträge anzeigen.
- [ ] Unter den Featured News beiträgen einen Button zu allen News Beiträgen anzeigen (/news)
- [ ] Seite erstellen die alle News Beiträge Anzeigt
